name: React CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crs-web
    strategy:
      matrix:
        node-version: ["14.x", "15.x"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build, and test
        run: |
          npm ci
          npm run build --if-present
          npm test
